---
# Install and configure rsnapshot

- name: Backup Server | rsnapshot | Install package
  yum: name=rsnapshot state=present

- name: Backup Server | rsnapshot | Update config file
  template: src=rsnapshot.conf dest=/etc/rsnapshot.conf owner=root group=root mode=0644

- name: Backup Server | rsnapshot | Create backup scripts directory
  file: path=/backups/.scripts owner=root group=root mode=0700 state=directory

- name: Backup Server | rsnapshot | Add mysqldump backup script
  template: src=mysqldump.sh dest=/backups/.scripts/mysqldump.sh owner=root group=root mode=0700

- name: Backup Server | rsnapshot | Add cron jobs
  cron: name="{{ item.name }}"
        job="{{ item.job }}"
        minute="{{ item.minute }}"
        hour="{{ item.hour }}"
        day="{{ item.day }}"
        month="{{ item.month }}"
        weekday="{{ item.weekday }}"
  with_items: rsnapshot.cron
