---

- name: HAProxy | Install
  yum: name=haproxy state=present

- name: Iptables | Get current rules
  shell: iptables-save
  register: iptablesrules
  always_run: yes

- name: Iptables | Insert iptables rule for HTTP on port 80
  shell: iptables -I INPUT -p tcp --dport 80 -j ACCEPT -m comment --comment "Unique ID HAPROXYHTTP HAProxy rule accept incoming HTTP traffic"
  when: iptablesrules.stdout.find("HAPROXYHTTP") == -1 

- name: Iptables | Insert iptables rule for HTTP on port 514
  shell: iptables -I INPUT -p udp --dport 514 -j ACCEPT -m comment --comment "Unique ID HAPROXYUDP HAProxy rule accept UDP logging messages"
  when: iptablesrules.stdout.find("HAPROXYUDP") == -1 

- name: Iptables | Explicitly save current rules
  shell: service iptables save
  notify: restart iptables

- name: HAProxy | Update config file
  copy: src="{{ haproxy_config }}" dest=/etc/haproxy/haproxy.cfg owner=root group=root mode=0644
  notify: restart haproxy

- name: HAProxy | Add rsyslog config
  copy: src=rsyslog-haproxy.conf dest=/etc/rsyslog.d/haproxy.conf owner=root group=root mode=0644
  notify: restart haproxy

  # Logging requires configuring the rsyslog daemon first
  # For more information see:
  # - http://sharadchhetri.com/2013/10/16/how-to-enable-logging-of-haproxy-in-rsyslog/
  # - http://transloadit.com/blog/2010/08/haproxy-logging/

- name: HAProxy | Add HAProxy logrotate config
  copy: src=logrotate-haproxy dest=/etc/logrotate.d/haproxy owner=root group=root mode=0644
  notify: restart haproxy

- name: HAProxy | Add HAProxy status logrotate config
  copy: src=logrotate-haproxy-status dest=/etc/logrotate.d/haproxystatus owner=root group=root mode=0644
  notify: restart haproxy

- name: HAProxy | Make sure service is running and on boot
  service: name=haproxy state=started enabled=yes
