---

- name: Apache | Install
  yum: name={{ item }} state=present
  with_items:
   - httpd
   - mod_wsgi

- name: Apache | Remove indexes option
  lineinfile: dest=/etc/httpd/conf/httpd.conf backrefs=yes
              regexp='Options Indexes FollowSymLinks'
              line='Options FollowSymLinks'
  notify: restart httpd

- name: Apache | Do not display Apache version
  lineinfile: dest=/etc/httpd/conf/httpd.conf backrefs=yes
              regexp='ServerTokens'
              line='ServerTokens Prod'
  notify: restart httpd

- name: Apache | Turn on NameVirtualHost option
  lineinfile: dest=/etc/httpd/conf/httpd.conf backrefs=yes
              regexp='#?NameVirtualHost'
              line='NameVirtualHost *:80'
  notify: restart httpd

- name: Apache | Remove default welcome page
  file: path=/etc/httpd/conf.d/welcome.conf state=absent

- name: Iptables | Insert iptables rule for httpd
  lineinfile: dest=/etc/sysconfig/iptables create=yes state=present regexp="{{ httpd_port }}" insertafter="^:OUTPUT "
              line="-A INPUT -p tcp  --dport {{ httpd_port }} -j  ACCEPT"
  notify: restart iptables

- name: SELinux | Allow httpd to remote network connect
  seboolean: name=httpd_can_network_connect state=true persistent=yes 

- name: SELinux | Allow httpd to remote network connect to database
  seboolean: name=httpd_can_network_connect_db state=true persistent=yes 

- name: Apache | Make sure httpd service is running
  service: name=httpd state=started enabled=yes
