---

- name: configure nagios servers
  hosts: nagiosservers
  remote_user: ansible
  sudo: yes
  roles:
    - apache
    - php_fpm
    - nagios_server

- name: configure nagios clients
  hosts: nagiosclients
  remote_user: ansible
  sudo: yes
  roles:
    - nagios_client

- name: configure munin servers
  hosts: muninservers
  remote_user: ansible
  sudo: yes
  roles:
    - apache
    - php_fpm
    - munin_server

- name: configure munin clients
  hosts: muninclients
  remote_user: ansible
  sudo: yes
  roles:
    - munin_client
