---

- name: configure nagios servers
  hosts: nagiosservers
  remote_user: ansible
  sudo: yes
  roles:
    - web
    - nagios_server

- name: configure nagios clients
  hosts: nagiosclients
  remote_user: ansible
  sudo: yes
  roles:
    - nagios_client
