---

- name: configure nagios servers
  hosts: nagiosservers
  remote_user: ansible
  sudo: yes
  roles:
    - apache
    - php_fpm
    - nagios_server

- name: configure nagios clients
  hosts: nagiosclients
  remote_user: ansible
  sudo: yes
  roles:
    - nagios_client
