---
# This task installs and manages the Munin server

- name: Munin Server | Install Munin server package
  shell: yum install --exclude=perl-XML-SAX-Base --skip-broken --assumeyes munin 

  # CentOS 6 has a dependency issue, skipping this package version solves the
  # conflict and munin works fine with the already installed older version

- name: Munin Server | Install Munin server support packages
  yum: name={{ item }} state=present
  with_items:
   - rrdtool

- name: Munin Server | Update main config file
  template: src=munin.conf dest=/etc/munin/munin.conf owner=root group=root mode=0664

- name: Munin Server | Copy htpasswd creation script
  copy: src=htpasswd.sh dest=/etc/httpd/htpasswd.sh owner=root group=root mode=0700
  when: munin_apache_username|lower != "none"

- name: Munin Server | Create htpasswd
  command: "/etc/httpd/htpasswd.sh /etc/munin/munin-htpasswd {{ munin_apache_username }} {{ munin_apache_password }}"
  when: munin_apache_username|lower != "none"

- name: Munin Server | Add munin user to webserver group
  user: name=munin groups=munin,apache append=yes

- name: Munin Server | Start Apache service
  service: name=httpd state=started enabled=true
