---
# This task adds the remote Nagios NRPE client

- name: SELinux | Get a list of active modules
  shell: "semodule -l | grep {{ nrpe_selinux_name }}"
  when: nrpe_selinux_name|lower != "none"
  register: module_is_loaded
  ignore_errors: true

- name: SELinux | Copy module config to target
  synchronize: src="{{ nrpe_selinux_src }}" dest=/tmp
  when: nrpe_selinux_src|lower != "none" and module_is_loaded|failed

- name: SELinux | Check module config file
  shell: "checkmodule -M -m -o /tmp/{{ nrpe_selinux_name }}.mod /tmp/{{ nrpe_selinux_name }}.te"
  when: nrpe_selinux_src|lower != "none" and module_is_loaded|failed

- name: SELinux | Compile config file
  shell: "semodule_package -o /tmp/{{ nrpe_selinux_name }}.pp -m /tmp/{{ nrpe_selinux_name }}.mod"
  when: nrpe_selinux_src|lower != "none" and module_is_loaded|failed

- name: SELinux | Load config file
  shell: "semodule -i /tmp/{{ nrpe_selinux_name }}.pp"
  when: nrpe_selinux_src|lower != "none" and module_is_loaded|failed

  # Taken from the audit2allow man page, this runs the commands:
  #     checkmodule -M -m -o /tmp/rule.mod /tmp/rule.te
  #     semodule_package -o /tmp/rule.pp -m /tmp/rule.mod
  #     semodule -i rule.pp

- name: Nagios Client | Install NRPE
  yum: name={{ item }} state=present
  with_items:
   - nrpe

- name: Nagios Client | Update NRPE config file
  template: src=nrpe.cfg dest=/etc/nagios/nrpe.cfg owner=root group=root mode=0644
  notify: restart nrpe

- name: Nagios Client | Sync plugins
  synchronize: src="{{ nrpe_plugins_src }}" dest="{{ nrpe_plugins_dest }}"
  when: nrpe_plugins_src|lower != "none"
  notify: restart nrpe

- name: Nagios Client | Update plugin file permissions
  file: path="{{ nrpe_plugins_dest }}" owner=nagios group=nagios mode=0750 recurse=yes

- name: Nagios Client | Update plugin directory permissions
  shell: "find {{ nrpe_plugins_dest }} -type d | xargs -I {} chmod 0755 {}"

- name: Nagios Client | Sync NRPE commands
  synchronize: src="{{ nrpe_commands_src }}" dest="{{ nrpe_commands_dest }}"
  when: nrpe_commands_src|lower != "none"
  notify: restart nrpe

- name: Nagios Client | Update NRPE command file permissions
  file: path="{{ nrpe_commands_dest }}" owner=root group=root mode=0644 recurse=yes

- name: Nagios Client | Update NRPE command directory permissions
  shell: "find {{ nrpe_commands_dest }} -type d | xargs -I {} chmod 0755 {}"

- name: Nagios Client | Start NRPE service
  service: name=nrpe state=started enabled=true

- name: Hosts | Add Nagios Server to hosts allowed
  lineinfile: dest=/etc/hosts.allow
              state=present
              regexp="^nrpe"
              line="nrpe:ALL"

- name: Iptables | Get current rules
  shell: iptables-save
  register: iptablesrules
  always_run: yes

  # Note: the always_run attribute ensures the shell command is executed
  # even when using ansible --check flag. See:
  # http://docs.ansible.com/playbooks_checkmode.html

- name: Iptables | Add NRPE port
  shell: iptables -I INPUT -p tcp  --dport {{ nrpe_port }} -j  ACCEPT -m comment --comment "Unique ID NRPE gateway rule accept incoming on private network eth2"
  when: iptablesrules.stdout.find("NRPE") == -1 

- name: Iptables | Explicitly save current rules
  shell: service iptables save
  notify: restart iptables
