---
# This task adds the remote Nagios NRPE client

- name: Nagios Client | Install NRPE
  yum: name={{ item }} state=present
  with_items:
   - nrpe

- name: Nagios Client | Update NRPE config file
  template: src=nrpe.cfg dest=/etc/nagios/nrpe.cfg owner=root group=root mode=0644
  notify: nrpe restart

- name: Nagios Client | Sync plugins
  synchronize: src="{{ nrpe.plugins.src }}" dest="{{ nrpe.plugins.dest }}"
