---
# This task adds the remote Nagios NRPE client

- name: Nagios Client | Install NRPE
  yum: name={{ item }} state=present
  with_items:
   - nrpe

- name: Nagios Client | Update NRPE config file
  template: src=nrpe.cfg dest=/etc/nagios/nrpe.cfg owner=root group=root mode=0644
  notify: restart nrpe

- name: Nagios Client | Sync plugins
  synchronize: src="{{ nrpe_plugins_src }}" dest="{{ nrpe_plugins_dest }}"
  when: nrpe_plugins_src|lower != "none"

- name: Nagios Client | Update plugin file permissions
  file: path="{{ nrpe_plugins_dest }}" owner=nagios group=nagios mode=0750 recurse=yes

- name: Nagios Client | Update plugin directory permissions
  shell: "find {{ nrpe_plugins_dest }} -type d | xargs -I {} chmod 0755 {}"

- name: Nagios Client | Sync NRPE commands
  synchronize: src="{{ nrpe_commands_src }}" dest="{{ nrpe_commands_dest }}"
  when: nrpe_commands_src|lower != "none"

- name: Nagios Client | Update NRPE command file permissions
  file: path="{{ nrpe_commands_dest }}" owner=root group=root mode=0644 recurse=yes

- name: Nagios Client | Update NRPE command directory permissions
  shell: "find {{ nrpe_commands_dest }} -type d | xargs -I {} chmod 0755 {}"

- name: Nagios Client | Start NRPE service
  service: name=nrpe state=started enabled=true

- name: Iptables | Add NRPE exception
  lineinfile: dest=/etc/sysconfig/iptables state=present regexp="{{ nrpe_port }}"
              insertafter="^:OUTPUT " line="-A INPUT -p tcp  --dport {{ nrpe_port }} -j  ACCEPT"
  notify: restart iptables
