---
# This task installs and configures php_fpm for apache

- name: PHP-FPM | Install
  yum: name={{ item }} state=present
  with_items:
   - php
   - php-cli
   - php-common
   - php-fpm
   - php-pdo

- name: PHP-FPM | Install supporting packages
  yum: name={{ item }} state=present
  with_items:
   - php-curl
   - php-gd
   - php-imagick
   - php-mcrypt
   - php-memcached
   - php-mysql
   - php-pear
   - php-pgsql
   - php-sqlite
   - php-xcache
  notify:
   - restart php-fpm
   - restart httpd
