---
# This task sets up SSH connection from the backup server to the client

# Add the public key of the backup user to client's authorized_keys file

- name: Backup Client | Create authorized_keys file
  file: path="/home/{{ ansible_ssh_user }}/.ssh/authorized_keys" state=touch owner="{{ ansible_ssh_user }}" group="{{ ansible_ssh_user }}" mode=0600
