---
# This task installs and manages the Nagios server

- name: Nagios Server | Install Nagios
  yum: name={{ item }} state=present
  with_items:
   - nagios

- name: Nagios Server | Update main config file
  template: src=nagios.cfg dest=/etc/nagios/nagios.cfg owner=root group=root mode=0664
  notify: restart nagios

- name: Nagios Server | Sync plugins
  synchronize: src="{{ nagios.plugins.src }}" dest="{{ nagios.plugins.dest }}"

- name: Nagios Server | Update plugin file permissions
  file: path="{{ nagios.plugins.dest }}" owner=nagios group=nagios mode=0750 recurse=yes

- name: Nagios Server | Update plugin directory permissions
  shell: "find {{ nagios.plugins.dest }} -type d | xargs -I {} chmod 0755 {}"

- name: Nagios Server | Remove base config files
  file: path="{{ item }}" state=absent
  with_items:
    - /etc/nagios/commands.cfg
    - "{{ nagios.config.dest }}contacts_nagios2.cfg"
    - "{{ nagios.config.dest }}generic-host_nagios2.cfg"
    - "{{ nagios.config.dest }}generic-service_nagios2.cfg"
    - "{{ nagios.config.dest }}timeperiods_nagios2.cfg"
    - "{{ nagios.config.dest }}check_mk/check_mk_templates.cfg"
    - "{{ nagios.objects.dir }}commands.cfg"
    - "{{ nagios.objects.dir }}contacts.cfg"
    - "{{ nagios.objects.dir }}localhost.cfg"
    - "{{ nagios.objects.dir }}printer.cfg"
    - "{{ nagios.objects.dir }}switch.cfg"
    - "{{ nagios.objects.dir }}templates.cfg"
    - "{{ nagios.objects.dir }}timeperiods.cfg"
    - "{{ nagios.objects.dir }}windows.cfg"

- name: Nagios Server | Remove example config files
  file: path="{{ item }}" state=absent
  with_items:
    - "{{ nagios.config.dest }}extinfo_nagios2.cfg"
    - "{{ nagios.config.dest }}hostgroups_nagios2.cfg"
    - "{{ nagios.config.dest }}localhost_nagios2.cfg"
    - "{{ nagios.config.dest }}services_nagios2.cfg"
    - "{{ nagios.config.dest }}localhost.cfg"

- name: Nagios Server | Sync config files
  synchronize: src="{{ nagios.config.src }}" dest="{{ nagios.config.dest }}"

- name: Nagios Server | Update config file permissions
  file: path="{{ nagios.config.dest }}" owner=root group=root mode=0644 recurse=yes

- name: Nagios Server | Update config directory permissions
  shell: "find {{ nagios.config.dest }} -type d | xargs -I {} chmod 0755 {}"

- name: Nagios Server | Update nagios cgi config file
  template: src=cgi.cfg dest=/etc/nagios/cgi.cfg owner=root group=root mode=0664
