---
# This playbook will install mysql and create db user and give permissions.

# MySQL Service

- name: MySQL | Install
  yum: name={{ item }} state=installed
  with_items:
   - mysql-server
   - MySQL-python

- name: MySQL | Create configuration file
  template: src=my.cnf dest=/etc/my.cnf
  notify: 
  - restart mysql

- name: SELinux | Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes

- name: Iptables | insert mysql iptables rule
  lineinfile: dest=/etc/sysconfig/iptables state=present regexp="{{ mysql_port }}"
              insertafter="^:OUTPUT " line="-A INPUT -p tcp  --dport {{ mysql_port }} -j  ACCEPT"
  notify: restart iptables

- name: MySQL | Start service
  service: name=mysqld state=started enabled=true
