---
# This playbook will install mysql and create db user and give permissions.

- name: MySQL | Install
  yum: name={{ item }} state=installed
  with_items:
   - mysql-server
   - MySQL-python

- name: MySQL | Create configuration file
  template: src=my.cnf dest=/etc/my.cnf
  notify: 
  - restart mysql
