---
      
# Basic Packages

- name: Install bash-completion package
  yum: name=bash-completion state=present

- name: Install bzip2 package
  yum: name=bzip2 state=present

- name: Install curl package
  yum: name=curl state=present

- name: Install git package
  yum: name=git state=present

- name: Install logwatch package
  yum: name=logwatch state=present

- name: Install python package
  yum: name=python state=present

- name: Install python pip package
  yum: name=python-pip state=present

- name: Install python virtualenv package
  yum: name=python-virtualenv state=present

- name: Install ntp package
  yum: name=ntp state=present

- name: Install rsync package
  yum: name=rsync state=present

- name: Install tmux package
  yum: name=tmux state=present

- name: Install wget package
  yum: name=wget state=present

- name: Install vim package
  yum: name=vim state=present

# Basic Services

- name: Start the ntp service
  service: name=ntpd state=started enabled=true
