---

# SELinux

- name: Install python bindings for selinux
  yum: name=libselinux-python state=present

- name: Install python bindings for semanage
  yum: name=libsemanage-python state=present

- name: Install python tools managing selinux
  yum: name=policycoreutils-python state=present
      
# Yum

- name: Copy the EPEL repository definition
  copy: src=epel.repo dest=/etc/yum.repos.d/

- name: Create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg/

- name: Copy the Remi repository definition
  copy: src=remi.repo dest=/etc/yum.repos.d/

- name: Create the GPG key for Remi
  copy: src=RPM-GPG-KEY-remi dest=/etc/pki/rpm-gpg/

- name: Copy the RPMforge repository definition
  copy: src=rpmforge.repo dest=/etc/yum.repos.d/

- name: Create the GPG key for RPMforge dag
  copy: src=RPM-GPG-KEY-rpmforge-dag dest=/etc/pki/rpm-gpg/

- name: Create the GPG key for RPMforge fabian
  copy: src=RPM-GPG-KEY-rpmforge-fabian dest=/etc/pki/rpm-gpg/
      
# Basic Packages

- name: Install bzip2 package
  yum: name=bzip2 state=present

- name: Install curl package
  yum: name=curl state=present

- name: Install git package
  yum: name=git state=present

- name: Install ntp package
  yum: name=ntp state=present

- name: Install rsync package
  yum: name=rsync state=present

- name: Install wget package
  yum: name=wget state=present

# Basic Services

- name: Start the ntp service
  service: name=ntpd state=started enabled=true
