---
      
# Basic Packages

- name: Install bash-completion package
  apt: name=bash-completion state=present

- name: Install bzip2 package
  apt: name=bzip2 state=present

- name: Install curl package
  apt: name=curl state=present

- name: Install git package
  apt: name=git state=present

- name: Install logwatch package
  apt: name=logwatch state=present

- name: Install python package
  apt: name=python state=present

- name: Install python pip package
  apt: name=python-pip state=present

- name: Install python virtualenv package
  apt: name=python-virtualenv state=present

- name: Install ntp package
  apt: name=ntp state=present

- name: Install rsync package
  apt: name=rsync state=present

- name: Install tmux package
  apt: name=tmux state=present

- name: Install wget package
  apt: name=wget state=present

- name: Install vim package
  apt: name=vim state=present

# Basic Services

- name: Start the ntp service
  service: name=ntp state=started enabled=true
