---

# SELinux

- name: Install python bindings for selinux
  yum: name=libselinux-python state=present

- name: Install python bindings for semanage
  yum: name=libsemanage-python state=present

- name: Install python tools managing selinux
  yum: name=policycoreutils-python state=present
      
# Yum

- name: Copy the EPEL repository definition
  copy: src=epel.repo dest=/etc/yum.repos.d/

- name: Create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg/

- name: Copy the Remi repository definition
  copy: src=remi.repo dest=/etc/yum.repos.d/

- name: Create the GPG key for Remi
  copy: src=RPM-GPG-KEY-remi dest=/etc/pki/rpm-gpg/

