---

httpd_port: 80
httpd_selinux_src: roles/apache/files/ApacheModWsgiRule.te
httpd_selinux_name: ApacheModWsgiRule
sendmail_selinux_src: roles/apache/files/SendmailRule.te
sendmail_selinux_name: SendmailRule
